name: Publish PowerShell Module

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Required Module
      shell: pwsh
      run: |
        Install-Module -Name PowerShellGet -Force -Scope CurrentUser -AllowClobber

    - name: Publish to PowerShell Gallery
      shell: pwsh
      env:
        PSGALLERY_API_KEY: ${{ secrets.PSGALLERY_API_KEY }}
      run: |
        # Find the module manifest (.psd1)
        $manifest = Get-ChildItem -Path . -Filter *.psd1 -Recurse | Select-Object -First 1

        if (-not $manifest) {
          Write-Error "Module manifest not found!"
          exit 1
        }

        Write-Host "Publishing module from: $($manifest.FullName)"
        Publish-Module -Path $manifest.Directory.FullName -NuGetApiKey $env:PSGALLERY_API_KEY

        $nupkg = Get-ChildItem -Path $manifest.Directory.FullName -Filter *.nupkg | Select-Object -First 1
        "$($nupkg.FullName)" | Out-File -FilePath "$env:GITHUB_ENV" -Append -Encoding utf8
        echo "NUPKG_PATH=$($nupkg.FullName)" >> $env:GITHUB_ENV

    - name: Create GitHub Release and upload NuPkg
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.NUPKG_PATH }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}